# Default values for onos-topo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: onosproject/onos-topo
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "onos-topo"

debug: false

store:
  enabled: true
  raftgroup: onos-topo-raft
  controller: atomix-controller.kube-system.svc.cluster.local:5679
  raft:
    partitions: 1
    clusters: 1
    replicas: 1
    backend:
      image: atomix/raft-replica:latest

ingress:
  enabled: false

resources: {}

service:
  type: ClusterIP

nodeSelector: {}

tolerations: []

affinity: {}
