sudo: false

branches:
  only:
    - master

services:
  - docker
  
notifications:
  email: false

install:
- docker pull quay.io/helmpack/chart-testing:v2.4.0

before_script:
  - pushd .. && git clone https://github.com/onosproject/build-tools.git && popd


jobs:
  include:
    - stage: chart tests
      script:
        - make test
        - ls -a
        - docker run -it --rm --name ct --volume $(pwd):/charts quay.io/helmpack/chart-testing:v3.0.0-beta.1 sh -c "ct lint --charts charts/onos-config,charts/onos-topo,charts/onos-cli,charts/onos-gui,charts/device-simulator --debug --validate-maintainers=false"
    - stage: integration tests
      if: type != pull_request
      script:
        - sh ../build-tools/build/travis/trigger-travis onosproject onos-test master "`git rev-parse --short HEAD`" $TRAVIS_ACCESS_TOKEN
