apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "onos-ric.fullname" . }}-config
  labels:
    app: {{ template "onos-ric.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  onos.yaml: |-
    atomix:
      controller: {{ .Values.store.controller }}
      namespace: {{ .Release.Namespace }}
      scope: {{ template "onos-ric.fullname" . }}
      databases:
        {{- if .Values.store.cache.database }}
        cache: {{ .Values.store.cache.database }}
        {{- else }}
        cache: {{ template "onos-ric.fullname" . }}-cache
        {{- end }}
        {{- if .Values.store.consensus.database }}
        consensus: {{ .Values.store.consensus.database }}
        {{- else }}
        consensus: {{ template "onos-ric.fullname" . }}-consensus
        {{- end }}
  logging.yaml: |-
{{- if .Values.logging }}
    logging:
{{ toYaml .Values.logging | indent 6 }}
{{- end}}
