apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "onos-ric.fullname" . }}-config
  labels:
    app: {{ template "onos-ric.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  config.yaml:
{{ toYaml .Values.config | indent 4 }}