apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "onos-topo.fullname" . }}-config
  labels:
    app: {{ template "onos-topo.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  onos.yaml: |-
    {{ toYaml .Values.logging | nindent 4 }}
  atomix.yaml: |-
    {{ toYaml .Values.atomix.logging | nindent 4 }}
  logging.yaml: |-
    {{ toYaml .Values.logging | nindent 4 }}
