apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "onos-topo.fullname" . }}-config
  labels:
    app: {{ template "onos-topo.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  onos.yaml: |-
    atomix:
      {{- if .Values.global.storage.controller }}
      controller: {{ .Values.global.storage.controller }}
      {{- else }}
      controller: {{ .Values.storage.controller }}
      {{- end }}
      namespace: {{ .Release.Namespace }}
      scope: {{ template "onos-topo.fullname" . }}
      {{- if .Values.storage.consensus.enabled }}
      databases:
        {{- if .Values.storage.consensus.name }}
        config: {{ .Values.storage.consensus.name }}
        {{- else }}
        config: {{ template "onos-topo.fullname" . }}-consensus-db
        {{- end }}
      {{- else if .Values.global.storage.consensus.enabled }}
      databases:
        {{- if .Values.global.storage.consensus.name }}
        config: {{ .Values.global.storage.consensus.name }}
        {{- else }}
        config: {{ template "global.fullname" . }}-consensus-db
        {{- end }}
      {{- end }}
  logging.yaml: |-
    {{ toYaml .Values.logging | nindent 4 }}
