apiVersion: v1
kind: Service
metadata:
  name: {{ include "ran-simulator.fullname" . }}
  labels:
    app: {{ template "ran-simulator.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- include "ran-simulator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    name: {{ template "ran-simulator.fullname" . }}
    app: onos
    type: sim
    resource: {{ template "ran-simulator.fullname" . }}
    {{- include "ran-simulator.selectorLabels" . | nindent 4 }}
  ports:
    - name: trafficsim
      port: 5150
    - name: exporter
      port: 9090
    {{- range $i, $j := until (int .Values.towerPort.numTowers) }}
    - name: tower-{{ $i }}
      port: {{ add (int $.Values.towerPort.startPort) $i }}
    {{- end }}
# Other ports will be added here dynamically by the application for E2 interface
