# Default values for onos-ric.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  depCheck: quay.io/stackanetes/kubernetes-entrypoint:v0.3.1
  repository: onosproject/onos-ric
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "onos-ric"

debug: false
topoEndpoint: "onos-topo:5150"
enableMetrics: false

store:
  controller: "atomix-controller.kube-system.svc.cluster.local:5679"
  cache:
    enabled: true
    database: ""
    partitions: 1
    clusters: 1
    backend:
      image: atomix/local-replica:latest
  consensus:
    enabled: true
    database: ""
    partitions: 1
    clusters: 1
    backend:
      image: atomix/raft-replica:latest
      replicas: 1

service:
  type: ClusterIP

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

logging: {}
