apiVersion: v2
name: app-operator
version: 0.4.11
kubeVersion: ">=1.17.0"
appVersion: v0.4.11
description: ÂµONOS App Operator
keywords:
  - onos
  - sdn
home: https://onosproject.org
maintainers:
  - name: ONOS Support
    email: support@opennetworking.org
