apiVersion: v2
name: topo-operator
version: 0.4.3
kubeVersion: ">=1.17.0"
appVersion: v0.4.5
description: ÂµONOS Topology Operator
keywords:
  - onos
  - sdn
home: https://onosproject.org
maintainers:
  - name: ONOS Support
    email: support@opennetworking.org
