# SPDX-FileCopyrightText: 2022 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: topo-operator
version: 0.5.4
kubeVersion: ">=1.17.0"
appVersion: v0.5.3
description: ÂµONOS Topology Operator
keywords:
  - onos
  - sdn
home: https://onosproject.org
maintainers:
  - name: ONOS Support
    email: support@opennetworking.org
