# Default values for ran-simulator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  depCheck: quay.io/stackanetes/kubernetes-entrypoint:v0.3.1
  repository: onosproject/ran-simulator
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []

fade: true
googleApiKey: "YOUR_API_KEY_HERE"
locationsScale: 1.0
mapCenterLat: 52.52
mapCenterLng: 13.405
maxUEsPerTower: 5
maxUEs: 300
metricsAllHoEvents: false
metricsPort: 9090
minUEs: 3
showPower: true
showRoutes: true
stepDelayMs: 1000
towerCols: 3
towerRows: 3
towerSpacingHoriz: 0.02
towerSpacingVert: 0.02
zoom: 13

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "ran-simulator"

store: {}

ingress:
  enabled: false

service:
  type: ClusterIP

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
